// Generated by scripts/pixelate-crests.py — do not edit.
// The clubs we have a pixelated badge on disk for; see lib/crests.ts.
export const PIXELATED_CRESTS = new Set<string>([
  "ARS",
  "AVL",
  "BHA",
  "BOU",
  "BRE",
  "CHE",
  "COV",
  "CRY",
  "EVE",
  "FUL",
  "HUL",
  "IPS",
  "LEE",
  "LIV",
  "MCI",
  "MUN",
  "NEW",
  "NOT",
  "SUN",
  "TOT",
]);
